apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: waygood-backend:latest  
        imagePullPolicy: Never        
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongodb://mongodb:27017/ai_assignment"
        - name: REDIS_URL
          value: "redis://redis:6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: waygood-worker:latest
        imagePullPolicy: Never
        env:
        - name: REDIS_HOST
          value: "redis"
